Watching for file changes with StatReloader
Index page accessed
"GET / HTTP/1.1" 200 18
Visited the "About Me" page
"GET /about/ HTTP/1.1" 200 17
Visited the "About Me" page
"GET /about/ HTTP/1.1" 200 17
Visited the "About Me" page
"GET /about/ HTTP/1.1" 200 17
Visited the "About Me" page
"GET /about/ HTTP/1.1" 200 17
Index page accessed
"GET / HTTP/1.1" 200 18
Index page accessed
"GET / HTTP/1.1" 200 18
Watching for file changes with StatReloader
Index page accessed
"GET / HTTP/1.1" 200 18
Index page accessed
"GET / HTTP/1.1" 200 18
Index page accessed
"GET / HTTP/1.1" 200 18
Not Found: /hello
"GET /hello HTTP/1.1" 404 2423
"GET /about HTTP/1.1" 301 0
Visited the "About Me" page
"GET /about/ HTTP/1.1" 200 17
Visited the "About Me" page
"GET /about/ HTTP/1.1" 200 17
Not Found: /about/e
"GET /about/e HTTP/1.1" 404 2429
Index page accessed
"GET / HTTP/1.1" 200 18
Index page accessed
"GET / HTTP/1.1" 200 18
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Index page accessed
"GET / HTTP/1.1" 200 18
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2546
Not Found: /shop/
"GET /shop/ HTTP/1.1" 404 2640
"GET /shop/order/customer/1 HTTP/1.1" 301 0
Internal Server Error: /shop/order/customer/1/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 9, in get_order_by_user
    return render(request, "shopapp/customer_order.html", {"order": order, "customer": customer})
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\defaulttags.py", line 1369, in url
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'url' takes at least one argument, a URL pattern name.
"GET /shop/order/customer/1/ HTTP/1.1" 500 167498
Watching for file changes with StatReloader
Internal Server Error: /shop/order/customer/1/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 9, in get_order_by_user
    return render(request, "shopapp/customer_order.html", {"order": order, "customer": customer})
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\defaulttags.py", line 1369, in url
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'url' takes at least one argument, a URL pattern name.
"GET /shop/order/customer/1/ HTTP/1.1" 500 167500
Watching for file changes with StatReloader
Internal Server Error: /shop/order/customer/1/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 9, in get_order_by_user
    return render(request, "shopapp/customer_order.html", {"order": order, "customer": customer})
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\template\defaulttags.py", line 1369, in url
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'url' takes at least one argument, a URL pattern name.
"GET /shop/order/customer/1/ HTTP/1.1" 500 167680
Watching for file changes with StatReloader
"GET /shop/order/customer/1/ HTTP/1.1" 200 180
"GET /shop/order/customer/4 HTTP/1.1" 301 0
"GET /shop/order/customer/4/ HTTP/1.1" 200 186
Watching for file changes with StatReloader
"GET /shop/order/customer/4/ HTTP/1.1" 200 186
Not Found: /shop/order/customer/
"GET /shop/order/customer/ HTTP/1.1" 404 2685
"GET /shop/order/customer/12 HTTP/1.1" 301 0
"GET /shop/order/customer/12/ HTTP/1.1" 200 180
"GET /shop/order/customer/14 HTTP/1.1" 301 0
"GET /shop/order/customer/14/ HTTP/1.1" 200 182
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /shop/order/customer/14/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 9, in get_order_by_user
    return render(request, "shopapp/customer_order.html", {"order": order, "customer": customer})
NameError: name 'order' is not defined
"GET /shop/order/customer/14/ HTTP/1.1" 500 65252
Internal Server Error: /shop/order/customer/1/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 9, in get_order_by_user
    return render(request, "shopapp/customer_order.html", {"order": order, "customer": customer})
NameError: name 'order' is not defined
"GET /shop/order/customer/1/ HTTP/1.1" 500 65169
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /shop/order/customer/1/ HTTP/1.1" 200 399
"GET /shop/order/customer/2 HTTP/1.1" 301 0
"GET /shop/order/customer/2/ HTTP/1.1" 200 472
Watching for file changes with StatReloader
"GET /shop/order/customer/2/ HTTP/1.1" 200 536
"GET /shop/order/customer/1/ HTTP/1.1" 200 447
"GET /shop/order/customer/1/ HTTP/1.1" 200 387
"GET /shop/order/customer/1/ HTTP/1.1" 200 437
"GET /shop/order/customer/1/ HTTP/1.1" 200 387
"GET /shop/order/customer/1/ HTTP/1.1" 200 447
"GET /shop/order/customer/1/ HTTP/1.1" 200 399
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /shop/order/customer/1/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: get_order_by_user() got an unexpected keyword argument 'customer_pk'
"GET /shop/order/customer/1/ HTTP/1.1" 500 62172
Internal Server Error: /shop/order/customer/1/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: get_order_by_user() got an unexpected keyword argument 'customer_pk'
"GET /shop/order/customer/1/ HTTP/1.1" 500 62028
Not Found: /shop/order/
"GET /shop/order/ HTTP/1.1" 404 2658
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /shop/order/
"GET /shop/order/ HTTP/1.1" 404 2649
Internal Server Error: /shop/order/customer/1/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 8, in get_order_by_user
    orders_week = Order.objects.filter(user=user, order_date__gte='2024-02-19').all()
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1427, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1237, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1725, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'order_date' into field. Choices are: customer, customer_id, date_order, id, products, total_price
"GET /shop/order/customer/1/ HTTP/1.1" 500 112364
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /shop/order/customer/1/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 8, in get_order_by_user
    orders_week = Order.objects.filter(user=user, date_order__gte='2024-02-19').all()
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1427, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1237, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1725, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, date_order, id, products, total_price
"GET /shop/order/customer/1/ HTTP/1.1" 500 112997
Internal Server Error: /shop/order/customer/1/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 8, in get_order_by_user
    orders_week = Order.objects.filter(user=user, date_order__gte='2024-02-19').all()
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1427, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1237, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1725, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, date_order, id, products, total_price
"GET /shop/order/customer/1/ HTTP/1.1" 500 112997
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /shop/order/customer/1/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 10, in get_order_by_user
    orders_year = Order.objects.filter(customer=user, date_order__gte='2023-02-26').all()
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1427, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1237, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\db\models\sql\query.py", line 1725, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, date_order, id, products, total_price
"GET /shop/order/customer/1/ HTTP/1.1" 500 113367
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /shop/order/customer/1/ HTTP/1.1" 200 238
"GET /shop/order/customer/1/ HTTP/1.1" 200 238
"GET /shop/order/customer/2/ HTTP/1.1" 200 7267
"GET /shop/order/customer/3 HTTP/1.1" 301 0
"GET /shop/order/customer/3/ HTTP/1.1" 200 238
"GET /shop/order/customer/4/ HTTP/1.1" 200 238
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /shop/order/customer/4/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: get_order_by_user() got an unexpected keyword argument 'pk'
"GET /shop/order/customer/4/ HTTP/1.1" 500 62120
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /shop/order/customer/4/ HTTP/1.1" 200 238
"GET /shop/order/customer/1/ HTTP/1.1" 200 238
"GET /shop/order/customer/2/ HTTP/1.1" 200 7267
"GET /shop/order/customer/2/ HTTP/1.1" 200 27735
"GET /shop/order/customer/2/ HTTP/1.1" 200 27735
"GET /shop/order/customer/1/ HTTP/1.1" 200 3590
Watching for file changes with StatReloader
"GET /shop/order/customer/1/ HTTP/1.1" 200 389
"GET /shop/order/customer/2/ HTTP/1.1" 200 389
"GET /shop/order/customer/2/ HTTP/1.1" 200 389
"GET /shop/order/customer/2/ HTTP/1.1" 200 389
"GET /shop/order/customer/3/ HTTP/1.1" 200 389
"GET /shop/order/customer/4/ HTTP/1.1" 200 395
"GET /shop/order/customer/4/ HTTP/1.1" 200 395
"GET /shop/order/customer/1/ HTTP/1.1" 200 389
Watching for file changes with StatReloader
"GET /shop/order/customer/1/ HTTP/1.1" 200 3598
"GET /shop/order/customer/2/ HTTP/1.1" 200 27743
"GET /shop/order/customer/2/ HTTP/1.1" 200 27743
"GET /shop/order/customer/2/ HTTP/1.1" 200 27743
"GET /shop/order/customer/14/ HTTP/1.1" 200 391
"GET /shop/order/customer/15 HTTP/1.1" 301 0
"GET /shop/order/customer/15/ HTTP/1.1" 200 9657
"GET /shop/order/customer/16 HTTP/1.1" 301 0
"GET /shop/order/customer/16/ HTTP/1.1" 200 1088
"GET /shop/order/customer/2/ HTTP/1.1" 200 27743
"GET /shop/order/customer/20 HTTP/1.1" 301 0
Not Found: /shop/order/customer/20/
"GET /shop/order/customer/20/ HTTP/1.1" 404 2861
"GET /shop/order/customer/19 HTTP/1.1" 301 0
Not Found: /shop/order/customer/19/
"GET /shop/order/customer/19/ HTTP/1.1" 404 2861
"GET /shop/order/customer/15/ HTTP/1.1" 200 9657
"GET /shop/order/customer/9 HTTP/1.1" 301 0
"GET /shop/order/customer/9/ HTTP/1.1" 200 4005
"GET /shop/order/customer/5 HTTP/1.1" 301 0
"GET /shop/order/customer/5/ HTTP/1.1" 200 393
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /shop/order/customer/5/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 9, in get_order_by_user
    week_date = datetime.today() - datetime.timedelta(days=7)
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
"GET /shop/order/customer/5/ HTTP/1.1" 500 66529
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /shop/order/customer/5/
Traceback (most recent call last):
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py", line 9, in get_order_by_user
    week_date = datetime.today() - datetime.timedelta(days=7)
AttributeError: module 'datetime' has no attribute 'today'
"GET /shop/order/customer/5/ HTTP/1.1" 500 66443
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /shop/order/customer/5/ HTTP/1.1" 200 393
"GET /shop/order/customer/1/ HTTP/1.1" 200 3598
"GET /shop/order/customer/2/ HTTP/1.1" 200 27743
Watching for file changes with StatReloader
"GET /shop/order/customer/3/ HTTP/1.1" 200 6574
"GET /shop/order/customer/3/ HTTP/1.1" 200 6574
"GET /shop/order/customer/1/ HTTP/1.1" 200 3598
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /shop/order/customer/1/ HTTP/1.1" 200 4404
C:\Users\Dakar\Desktop\git_HW\Django_HW\HW_1\myproject\shopapp\views.py changed, reloading.
Watching for file changes with StatReloader
